name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test